version: "3.8"

services:

  linux_server:
    build: 
      context: .
      dockerfile: Dockerfile 
    
    # image: sunny1928/smart_farm
    ports:
      - 8088:8088
    # volumes:
      # - .:/app
      # - '/app/node_modules' # ignore node_modules
    depends_on:
      - linux_sql
    restart: on-failure


  linux_sql:
    image: mysql
    environment:
      - MYSQL_DATABASE=smart_farm_db 
      - MYSQL_ROOT_PASSWORD=a10955

  